<?php

$npcinfo = array
	( 
	1 => array
		(
		'type' => 1,
		'num' => 1,
		'round' => 0,
		'gd' => 'm',
		'pls' => 0,
		'mhp' => 4000,
		'msp' => 200,
		'att' => 200,
		'def' => 200,
		'lvl' => 40,
		'proficiency' => 300,
		'skill' => array('Peg'),
		'money' => 1,
		'arb' => '帝将战甲B',
		'arbk' => 'DB',
		'arbe' => 50,
		'arbs' => 100,
		'arh' => '帝将战甲H',
		'arhk' => 'DH',
		'arhe' => 25,
		'arhs' => 100,
		'arf' => '帝将战甲F',
		'arfk' => 'DF',
		'arfe' => 25,
		'arfs' => 100,
		'ara' => '帝将战甲A',
		'arak' => 'DA',
		'arae' => 25,
		'aras' => 100,
		'art' => '代理将军的勋章',
		'artk' => 'A',
		'arte' => 20,
		'arts' => 10,
		'artsk' => array('buff-def' => 10),
		'sub' => array
			(
			0 => array
				(
				'name' => '哈奴·曼科尔',
				'icon' => 1,
				'species' => 31,
				'side' => 1,
				'wep' => '曼科尔的左轮手枪',
				'wepk' => 'WG',
				'wepe' => 150,
				'weps' => 65535,
				'itm1' => '「BATTLE ROYALE」控制装置',
				'itmk1' => 'Y',
				'itme1' => 1,
				'itms1' => 1,
				),
			),
		),
	2 => array
		(
		'type' => 2,
		'num' => 1,
		'round' => 0,
		'gd' => 'm',
		'pls' => 0,
		'mhp' => 800,
		'msp' => 200,
		'att' => 150,
		'def' => 100,
		'lvl' => 16,
		'proficiency' => 100,
		'skill' => array('Peg'),
		'money' => 1000,
		'arb' => '空战斗篷',
		'arbk' => 'DB',
		'arbe' => 40,
		'arbs' => 100,
		'arh' => '空战风镜',
		'arhk' => 'DH',
		'arhe' => 20,
		'arhs' => 100,
		'arf' => '空战越野靴',
		'arfk' => 'DF',
		'arfe' => 20,
		'arfs' => 100,
		'ara' => '空战副翼',
		'arak' => 'DA',
		'arae' => 20,
		'aras' => 100,
		'art' => '朝圣者挂坠',
		'artk' => 'A',
		'arte' => 20,
		'arts' => 10,
		'artsk' => array('buff-def' => 10),
		'sub' => array
			(
			0 => array
				(
				'name' => 'A.B.森提娅',
				'icon' => 2,
				'species' => 12,
				'side' => 2,
				'wep' => '童话伪翼',
				'wepk' => 'WK',
				'wepe' => 75,
				'weps' => 25,
				),
			),
		),
	3 => array
	(
		'type' => 3,
		'num' => 1,
		'round' => 0,
		'gd' => 'm',
		'pls' => 1,
		'mhp' => 500,
		'msp' => 200,
		'att' => 120,
		'def' => 120,
		'lvl' => 8,
		'proficiency' => 75,
		'skill' => array('Peg'),
		'money' => 1000,
		'arb' => '旅行者斗篷',
		'arbk' => 'DB',
		'arbe' => 40,
		'arbs' => 100,
		'arh' => '黯淡的牛仔帽',
		'arhk' => 'DH',
		'arhe' => 20,
		'arhs' => 100,
		'arf' => '防火靴',
		'arfk' => 'DF',
		'arfe' => 20,
		'arfs' => 100,
		'ara' => '药剂师蹄套',
		'arak' => 'DA',
		'arae' => 20,
		'aras' => 100,
		'art' => '朝圣者挂坠',
		'artk' => 'A',
		'arte' => 20,
		'arts' => 10,
		'artsk' => array('buff-def' => 10),
		'sub' => array
		(
			0 => array
			(
				'name' => 'D.E.斯蒂妮',
				'icon' => 3,
				'species' => 11,
				'side' => 2,
				'wep' => '杀虫枪',
				'wepk' => 'WG',
				'wepe' => 50,
				'weps' => 100,
			),
		),
	),
	101 => array
		(
		'type' => 101,
		'mode' => 2,
		'num' => 60,
		'round' => 0,
		'gd' => 'r',
		'pls' => 'R1 2 3',
		'mhp' => 300,
		'msp' => 200,
		'att' => 125,
		'def' => 100,
		'lvl' => 10,
		'proficiency' => 50,
		'skill' => array('kedama'),
		'money' => 250,
		'arb' => '征召兵制服',
		'arbk' => 'DB',
		'arbe' => 20,
		'arbs' => 20,
		'arh' => '征召兵帽',
		'arhk' => 'DH',
		'arhe' => 10,
		'arhs' => 20,
		'arf' => '征召兵靴',
		'arfk' => 'DF',
		'arfe' => 10,
		'arfs' => 20,
		'ara' => '征召兵手套',
		'arak' => 'DA',
		'arae' => 10,
		'aras' => 20,
		'itm1' => '军用干粮',
		'itmk1' => 'HB',
		'itme1' => 125,
		'itms1' => 2,
		'sub' => array
			(
			0 => array
				(
				'name' => '帝国征召火枪兵',
				'icon' => 101,
				'wep' => '火枪',
				'wepk' => 'WG',
				'wepe' => 15,
				'weps' => 30,
				),
			1 => array
				(
				'name' => '帝国征召近战兵',
				'icon' => 102,
				'wep' => '狼牙棒',
				'wepk' => 'WP',
				'wepe' => 20,
				'weps' => 10,
				),
			2 => array
				(
				'name' => '帝国征召军刀兵',
				'icon' => 103,
				'wep' => '军刀',
				'wepk' => 'WK',
				'wepe' => 25,
				'weps' => 5,
				),
			3 => array
				(
				'name' => '帝国征召掷弹兵',
				'icon' => 104,
				'wep' => '质量弹',
				'wepk' => 'WC',
				'wepe' => 5,
				'weps' => 45,
				),
			),
		),
	102 => array
		(
		'type' => 102,
		'num' => 30,
		'round' => 1,
		'gd' => 'r',
		'pls' => 'RA',
		'mhp' => 600,
		'msp' => 200,
		'att' => 200,
		'def' => 200,
		'lvl' => 25,
		'proficiency' => 150,
		'skill' => array('kedama', 'Peg','disappear@1'),
		'money' => 600,
		'arb' => '帝国防弹衣',
		'arbk' => 'DB',
		'arbe' => 60,
		'arbs' => 30,
		'arbsk' => array('suit' => 'kedama'),
		'ara' => '帝国士兵手套',
		'arak' => 'DA',
		'arae' => 35,
		'aras' => 20,
		'arask' => array('suit' => 'kedama'),
		'arf' => '帝国士兵靴',
		'arfk' => 'DF',
		'arfe' => 35,
		'arfs' => 25,
		'arfsk' => array('suit' => 'kedama'),
		'arh' => '帝国士兵头盔',
		'arhk' => 'DH',
		'arhe' => 50,
		'arhs' => 30,
		'arhsk' => array('suit' => 'kedama'),
		'sub' => array
			(
			0 => array
				(
				'name' => '帝国正规军',
				'icon' => 111,
				'wep' => '莫洛克自动步枪',
				'wepk' => 'WG',
				'wepe' => 50,
				'weps' => 300,
				'wepsk' => array('suit' => 'kedama'),
				),
			),
		),
	);

?>